-- Сценарий определения ограничений

ALTER TABLE Clients ADD CONSTRAINT CHK_Address_Length CHECK (LENGTH(Адрес) <= 255);
ALTER TABLE Cars ADD CONSTRAINT CHK_Car_Year CHECK (Год_выпуска >= 1900 AND Год_выпуска <= EXTRACT(YEAR FROM NOW()));
ALTER TABLE Cars ADD CONSTRAINT CHK_VIN UNIQUE(VIN);
ALTER TABLE Masters ADD CONSTRAINT CHK_Experience CHECK (Опыт_работы >= 0);
ALTER TABLE Services ADD CONSTRAINT CHK_Cost CHECK (Стоимость > 1);
ALTER TABLE Services ADD CONSTRAINT CHK_Duration CHECK (Продолжительность > 0);
ALTER TABLE Orders ADD CONSTRAINT CHK_Order_Status CHECK (Статус_заказа IN ('Ожидает', 'В процессе', 'Завершено', 'Отменено'));


ALTER TABLE Clients ADD CONSTRAINT CHK_Name_NULL CHECK (Имя IS NOT NULL);
ALTER TABLE Clients ADD CONSTRAINT CHK_SecondName_NULL CHECK ( Фамилия IS  NOT NULL);
ALTER TABLE Clients ADD CONSTRAINT CHK_Tel_NULL CHECK ( Телефон IS  NOT NULL);


ALTER TABLE Cars ADD CONSTRAINT CHK_Mark_NULL CHECK ( Марка IS NOT NULL);
ALTER TABLE Cars ADD CONSTRAINT CHK_Mod_NULL CHECK ( Модель IS NOT NULL);



ALTER TABLE Masters ADD CONSTRAINT CHK_NameMaster_NULL CHECK (Имя IS NOT NULL);
ALTER TABLE Masters ADD CONSTRAINT CHK_SecondNameMAster_NULL CHECK ( Фамилия IS NOT NULL);
ALTER TABLE Masters ADD CONSTRAINT CHK_Spec_NULL CHECK ( Специализация IS NOT NULL);


ALTER TABLE Services ADD CONSTRAINT CHK_NameService_NULL CHECK ( Название IS NOT NULL);
ALTER TABLE Services ADD CONSTRAINT CHK_Opisanie_NULL CHECK ( Описание IS NOT NULL);


ALTER TABLE Orders ADD CONSTRAINT CHK_CarID_NULL CHECK ( CarID IS NOT NULL);
ALTER TABLE Orders ADD CONSTRAINT CHK_MasterId_NULL CHECK ( MasterID IS NOT NULL);
ALTER TABLE Orders ADD CONSTRAINT CHK_ServiceID_NULL CHECK ( ServiceID IS NOT NULL);
ALTER TABLE Orders ADD CONSTRAINT CHK_DatOrder_NULL CHECK ( Дата_заказа IS NOT NULL);
ALTER TABLE Orders ADD CONSTRAINT CHK_Status_NULL CHECK ( Статус_заказа IS NOT NULL)
